version: '3.0'

services:

  nginx:
    image: nginx
    environment:
      - VIRTUAL_HOST=site.local
    depends_on:
      - php
    volumes:
      - ./docker/nginx/conf.d/default.nginx:/etc/nginx/conf.d/default.conf
      - ./project/:/var/www/project/
    networks:
      - frontend
      - backend

  php:
    build:
      context: ./docker/php
      args:
        - GID=${GID}
        - UID=${UID}
    depends_on:
      - mysql
    volumes:
      - ./project/:/var/www/project/
    networks:
      - backend
    command: >
      bash -c "composer install && php-fpm"

  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend
    ports:
      - 8306:3306


networks:
  frontend:
    external:
      name: proxy_proxy
  backend: